CREATE TABLE "GCG_3623_EST_SUM"(
 "EST_NO" BIGINT,
 "SEQ" CHAR(6),
 "LMO" CHAR(1),
 "PART" CHAR(20),
 "REV" CHAR(3),
 "LOC" CHAR(2),
 "OPERATION1" CHAR(6),
 "SETUP" DOUBLE DEFAULT '0',
 "RUNTIME" DOUBLE DEFAULT '0',
 "RATE" DOUBLE DEFAULT '0',
 "FREQ" DOUBLE DEFAULT '0',
 "DESCRIPTION" CHAR(30),
 "UM" CHAR(2),
 "TOTAL_COST" DOUBLE DEFAULT '0',
 "DIRECT_COST" DOUBLE DEFAULT '0',
 "OH_COST" DOUBLE DEFAULT '0',
 "LABOR_HRS" DOUBLE DEFAULT '0',
 "MIN_COST" DOUBLE DEFAULT '0',
 "POS" INTEGER,
 "FINISH_PART" CHAR(20),
 "COMMENTS" CHAR(500));

CREATE INDEX "INDEXEST" USING 0 ON "GCG_3623_EST_SUM"("EST_NO");