CREATE TABLE "GCG_3623_RUN_MAINT"(
 "QTY_1" DOUBLE DEFAULT '0',
 "QTY_2" DOUBLE DEFAULT '0',
 "QTY_3" DOUBLE DEFAULT '0',
 "QTY_4" DOUBLE DEFAULT '0',
 "QTY_5" DOUBLE DEFAULT '0',
 "QTY_6" DOUBLE DEFAULT '0',
 "QTY_7" DOUBLE DEFAULT '0',
 "QTY_8" DOUBLE DEFAULT '0',
 "QTY_9" DOUBLE DEFAULT '0',
 "QTY_10" DOUBLE DEFAULT '0');
