CREATE TABLE "GCG_3623_WC_MAINT"(
 "WORKCENTER" VARCHAR(4) NOT NULL ,
 "LOCATION1" VARCHAR(2),
 "WORK_GROUP" INTEGER,
 "FINISH_GROUP" INTEGER,
 "ATTRIBUTE1" LONGVARCHAR,
 "ATT_VALUE" DOUBLE,
 "ATT_NUM" INTEGER);

CREATE INDEX "INDEXWC" USING 0 ON "GCG_3623_WC_MAINT"("WORKCENTER", "LOCATION");