CREATE TABLE "GCG_3623_GRP_MAINT"(
 "GRP" CHAR(8) NOT NULL ,
 "CUST_MAST" BIT NOT NULL ,
 "CRM" BIT NOT NULL ,
 "INV_MAST" BIT NOT NULL ,
 "VEN_MAST" BIT NOT NULL ,
 "SUPP_DEM" BIT NOT NULL ,
 "WEBSITE" BIT NOT NULL ,
 "ADMIN1" BIT NOT NULL );

CREATE INDEX "INDEXGROUP" USING 0 ON "GCG_3623_GRP_MAINT"("GRP");