CREATE TABLE "GCG_3623_EST_PRICE"(
 "EST_NO" BIGINT,
 "DIRECT_COST" DOUBLE DEFAULT '0',
 "UNIT_COST" DOUBLE DEFAULT '0',
 "MAT_COST" DOUBLE DEFAULT '0',
 "OUT_COST" DOUBLE DEFAULT '0',
 "LABOR_COST" DOUBLE DEFAULT '0',
 "LABOR_HRS" DOUBLE DEFAULT '0',
 "OH_COST" DOUBLE DEFAULT '0',
 "TOTAL_COST" DOUBLE DEFAULT '0',
 "QTY" DOUBLE DEFAULT '0',
 "TOTAL_PRICE" DOUBLE DEFAULT '0',
 "MARKUP" DOUBLE DEFAULT '0',
 "MSI" DOUBLE DEFAULT '0',
 "MARGINA" DOUBLE DEFAULT '0',
 "MARGINP" DOUBLE DEFAULT '0',
 "FINISH_PART" CHAR(20),
 "UNIT_PRICE" DOUBLE DEFAULT '0',
 "FORMULA" LONGVARCHAR);

CREATE INDEX "INDEXEST" USING 0 ON "GCG_3623_EST_PRICE"("EST_NO");