CREATE TABLE "GCG_3623_EST_LABOR"(
 "EST_NO" BIGINT,
 "WC" CHAR(20),
 "OP_CODE" CHAR(50),
 "DESCRIPTION" CHAR(30),
 "STD_COST" DOUBLE DEFAULT '0',
 "STD_RATE" DOUBLE DEFAULT '0',
 "STD_RUN" DOUBLE DEFAULT '0',
 "CREW" DOUBLE DEFAULT '0',
 "SETUP" DOUBLE DEFAULT '0',
 "POS" INTEGER,
 "FORMULAR" LONGVARCHAR,
 "FORMULAS" LONGVARCHAR,
 "ROW1" INTEGER);

CREATE INDEX "INDEXEST" USING 0 ON "GCG_3623_EST_LABOR"("EST_NO");