CREATE TABLE "GCG_3623_JACKET_PART"(
 "FINISH_PART" CHAR(20),
 "PART" CHAR(20),
 "DESCRIPTION" CHAR(30),
 "SORT_CODE" CHAR(30),
 "QTY" DOUBLE DEFAULT '0',
 "ACROSS" DOUBLE DEFAULT '0',
 "FINISH_LOC" CHAR(2),
 "W_GROUP" CHAR(30),
 "WORK_CENTER" CHAR(30),
 "FINISH_REV" CHAR(3));

CREATE INDEX "Key01" USING 0 ON "GCG_3623_JACKET_PART"("FINISH_PART", "FINISH_LOC");